### ISSUE TITLE
Broken link on "Patterns for Building LLM-based Systems & Products"

### ISSUE THREAD

**Issue by jarrad** [eugeneyan/eugeneyan#1]
Thank you for sharing your insights. This article is fantastic!

I wanted to point out one issue I hit while reading:

The first link in the section [How to apply fine tuning?](https://eugeneyan.com/writing/llm-patterns/#how-to-apply-fine-tuning) with text "good guidelines" is incorrect.

It should link to [How to Write Data Labeling/Annotation Guidelines](https://eugeneyan.com/writing/labeling-guidelines/)

**Comment by eugeneyan** [comment]
Thank you for catching this and bringing it to my attention! 🙏 

Fixed.
